name: rnacompete

channels:
  - defaults
  - bioconda

dependencies:
  - meme=5.5
  - pip
  - pip:
    - absl-py
    - logomaker
    - matplotlib
    - numpy
    - scikit-learn
    - scipy
    - pandas
    - pickleshare
